---
title: "Baseline Model Performance"
author: "Gwen Rino"
date: "April 11, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages, echo=FALSE, warning=FALSE, message=FALSE}
library(ProjectTemplate)
```

```{r echo=FALSE, results='hide', message=FALSE}
setwd("../../..")
load.project()
```

## Model Description  
  
In order to establish a baseline measure of Mean Absolute Error (MAE) for dengue prediction models, I created a naive model that predicts the number of cases of dengue per week to be equal to the average number of cases for that season of the year.\

```{r}
# Find mean total_cases for fall, spring, summer, winter
dengue %>% dplyr::group_by(season) %>% 
  summarize(mean = mean(total_cases, na.rm = TRUE))

# Assign seasonal mean as prediction for each observation
dengue.naive <- dengue %>% 
  mutate(predictions = case_when(season == "fall" ~ 59.2,
                                 season == "spring" ~ 11.9,
                                 season == "summer" ~ 41.6,
                                 season == "winter" ~ 23.9))

predictions <- dengue.naive$predictions
```

## Model Evaluation  
  
The baseline MAE is 25.5.\

```{r}
# Error = actual number of cases - predicted number of cases
error <- dengue.naive$total_cases - predictions

# Find MAE
print(paste("Naive model MAE = ", mean(abs(error))))
```



