---
title: "Linear Model Performance"
author: "Gwen Rino"
date: "April 20, 2018"
output: 
  md_document:
    variant: markdown_github
---

The first linear model uses the features identified as having significant p-values in Pearson correlation tests against the target variable total_cases. The features used in the model are:   
  
- ndvi_nw **(significant p-value)**     
- reanalysis_air_temp_k  
- reanalysis_avg_temp_k     
- reanalysis_dew_point_temp_k  
- reanalysis_max_air_temp_k **(significant p-value)**    
- reanalysis_min_air_temp_k         
- reanalysis_relative_humidity_percent    
- reanalysis_specific_humidity_g_per_kg **(significant p-value)**  
- station_avg_temp_c  
- station_max_temp_c  
- station_min_temp_c  
- weekofyear **(significant p-value)**  
  
Applying this model to a test set, a comparison of the predicted to the actual number of cases yields a Mean Absolute Error (MAE) of 22.2.  
  
In order to meet the required model performance level established in the FPS, a future model must reduce the MAE by 18.2.

***

The second linear model uses the same features as above but adds the engineered feature year.season.  

Adding this feature greatly increases the predictive power of the model. Applying this model to a test set, a comparison of the predicted to the actual number of cases hields a Mean Absolute Error (MAE) of 12.1.  

In order to meet the required model performance level established in the FPS, a future model must reduce the MAE by 8.1.
