---
title: "Dengue Project - Assets"
author: "Gwen Rino"
date: "4/20/2018"
output: 
  md_document:
    variant: markdown_github
---

# Assets   

## INPUTS   

**DATA**   

**DrivenData files**   

* Path: Features: ~CSX415.1-project/dengue/data/dengue_features_train.csv   
        Labels: ~CSX415.1-project/dengue/data/dengue_labels_train.csv   
* Description: These are the data files from the [DengAI: Predicting Disease Spread](https://www.drivendata.org/competitions/44/dengai-predicting-disease-spread/) contest sponsored by [DrivenData](https://www.drivendata.org/).  

**Puerto Rico Tourism Company files**  

* Path: ~CSX415.1-project/dengue/data/hotel.guests.copy.csv  
* Description: This is data on monthly non-resident hotel guests I extracted from files from the [Statistics.PR website](https://estadisticas.pr/inventario-de-estadisticas/puerto_rico_tourism_company).  


## OUTPUTS  

**FORMAL PROBLEM STATEMENT**    
* Path: ~CSX415.1-project/dengue/reports/FormalProblemStatement.pdf   
* Description: This initial report includes an overview of the problem, background on the context, a list of stakeholders, the project's success metrics and risk estimates, an explanation of how the model will be deployed, and a timeline for the project.  

**EXPLORATORY DATA ANALYSIS**  
* Path: ~CSX415.1-project/dengue/src/EDA/EDA.R  
* Description: This R script includes initial exploratory data analysis, including tests for Pearson correlations between variables and for autocorrelations in the time series.  

**EDA VISUALIZATION**
* Path: ~CSX415.1-project/dengue/src/EDA/EDA.viz.R  
* Description: This R script includes a histogram of the response variable, scatterplots of the relationships between the predictor and response variables, and basic time series plots.  

**FEATURE SELECTION**
* Path: ~CSX415.1-project/dengue/src/FeatureSelection/FeatureSelection.R  
* Description: This R script utilizes the randomForest::importance() function and the earth::evimp() function develop a list of features that may be most important in modeling the data.  

**MODELS**  
* Paths: ~CSX415.1-project/dengue/src/Models/0.Naive.R  
         ~CSX415.1-project/dengue/src/Models/1.Linear.R  
         ~CSX415.1-project/dengue/src/Models/2.Tree.R  
         ~CSX415.1-project/dengue/src/Models/3.Arima.R  
         ~CSX415.1-project/dengue/src/Models/4.0.DynamicRegression.R  
         ~CSX415.1-project/dengue/src/Models/4.1.DynRegValidation.R  
         ~CSX415.1-project/dengue/src/Models/5.VAR.R  
* Description: Each of these R scripts fits one or more models according to a particular algorithm.  

**EVALUATION OF MODELS**  
* Paths: ~CSX415.1-project/dengue/reports/ModelEvaluations/0.NaiveEval.pdf  
         ~CSX415.1-project/dengue/reports/ModelEvaluations/1.LinearEval.pdf  
         ~CSX415.1-project/dengue/reports/ModelEvaluations/2.TreeEval.pdf  
         ~CSX415.1-project/dengue/reports/ModelEvaluations/3.ArimaEval.pdf  
         ~CSX415.1-project/dengue/reports/ModelEvaluations/4.DynRegEval.pdf  
         ~CSX415.1-project/dengue/reports/ModelEvaluations/5.VAREval.pdf  
* Description: Each of these reports describes one model and evaluates it according to its Mean Absolute Error (MAE).  

**PACKAGE FOR DEPLOYMENT OF MODEL**
* Path: ~CSX415.1-project/dengue/pkgs/Dengue
* Description: This package contains the function DengueFC(), which can be used to forecast weekly cases of dengue disease in San Juan, Puerto Rico, as well as to recommend the number of staff to be employed at the health clinic.

**ABOUT THE MODEL**
* Path: ~CSX415.1-project/dengue/reports/AboutModel.pdf
* Description: This report explains in general terms how the forecasting tool works, and interprets the potential impact of the tool by way of three examples of the cost savings that would have been incurred had the tool been in use at that time.









